steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--no-cache',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/ueabreu-frontend/ueabreu-frontend:latest',
      '--build-arg', 'VITE_API_BASE_LOCAL=https://appservices.ueabreu.com/api', # 👈 LÍNEA AÑADIDA
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/ueabreu-frontend/ueabreu-frontend:latest'
    ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'ueabreu-frontend',
      '--image',
      'us-central1-docker.pkg.dev/$PROJECT_ID/ueabreu-frontend/ueabreu-frontend:latest',
      '--region',
      'us-central1',
      '--platform',
      'managed',
      '--allow-unauthenticated',
      '--port',
      '8080'
      # ❌ ELIMINADO: '--set-env-vars', "VITE_API_BASE_LOCAL=..." 
      # Ya no es necesario aquí porque el valor ya está en la imagen.
    ]
options:
    logging: CLOUD_LOGGING_ONLY