steps:
  # ... Paso 1: Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--no-cache',
      '-t',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source/ueabreu-frontend:latest', # ¡Ruta AR nativa!
      '.'
    ]
  
  # ... Paso 2: Docker push
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source/ueabreu-frontend:latest' # ¡Ruta AR nativa!
    ]
  
  # ... Paso 3: Cloud Run deploy
  - name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - ueabreu-frontend
      - --image
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source/ueabreu-frontend:latest' # ¡Ruta AR nativa!
      - --region
      - us-central1
      - --platform
      - managed
      - --allow-unauthenticated
      - --port
      - '8080' 
options:
  logging: CLOUD_LOGGING_ONLY
