events {}
http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name  localhost;

        # La raíz del proyecto apunta a la carpeta de build final (donde está el index.html)
        root   /usr/share/nginx/html;
        index  index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        # Manejo de errores
        error_page 500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}