import { useState } from 'react';
import { toast } from 'react-toastify';
import { createRepresentativeRegistration } from '../../apis/representativeRegistration';

export default function RepresentativeRegistration() {
  const [data, setData] = useState({ fullName: '', identityCard: '', birthDate: '', nationality: '', birthCountry: '', state: '', zone: '', addressDescription: '', phone: '', emergencyContact: '', emergencyPhone: '', hasAllergies: false, allergiesDescription: '', hasDiseases: false, diseasesDescription: '', previousSchool: '', municipality: '', aspiredGrade: '', currentGrade: '', section: '' });
  const update = (key: string, value: string) => setData(prev => ({ ...prev, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const res = await createRepresentativeRegistration(data); if (res.result) toast.success(`Solicitud enviada. Planilla ${res.content.planillaNumber}`); else toast.error(res.error?.[0]); };
  const fields = [['fullName', 'Nombre completo *'], ['identityCard', 'Cédula *'], ['birthDate', 'Fecha de nacimiento *'], ['nationality', 'Nacionalidad *'], ['birthCountry', 'País de nacimiento *'], ['state', 'Estado *'], ['zone', 'Zona *'], ['phone', 'Teléfono'], ['emergencyContact', 'Contacto de emergencia *'], ['emergencyPhone', 'Teléfono de emergencia *'], ['previousSchool', 'Escuela de procedencia'], ['municipality', 'Municipio'], ['aspiredGrade', 'Año al que aspira *']];
  const input = (key: string, label: string) => <label key={key} className="text-sm font-semibold text-gray-700">{label}<input type={key === 'birthDate' ? 'date' : 'text'} required={label.includes('*')} value={data[key as keyof typeof data] as string} onChange={e => update(key, e.target.value)} className="mt-1 w-full px-3 py-2 border-2 border-gray-200 rounded-lg focus:border-blue-500 outline-none" /></label>;
  return <form onSubmit={submit} className="max-w-5xl mx-auto space-y-6"><div className="text-center"><h1 className="text-3xl font-bold text-gray-800">Solicitud de inscripción</h1><p className="text-gray-600 mt-2">Formulario para solicitar cupo de un nuevo estudiante asociado a su cuenta.</p></div><section className="bg-white rounded-xl shadow-md p-6"><h2 className="text-xl font-bold text-gray-800 border-b pb-3 mb-5">Datos personales</h2><div className="grid md:grid-cols-2 gap-5">{fields.slice(0, 5).map(([key, label]) => input(key, label))}</div></section><section className="bg-white rounded-xl shadow-md p-6"><h2 className="text-xl font-bold text-gray-800 border-b pb-3 mb-5">Dirección y contacto</h2><div className="grid md:grid-cols-2 gap-5">{fields.slice(5).map(([key, label]) => input(key, label))}<label className="md:col-span-2 text-sm font-semibold text-gray-700">Descripción de la dirección<textarea required value={data.addressDescription} onChange={e => update('addressDescription', e.target.value)} rows={3} className="mt-1 w-full px-3 py-2 border-2 border-gray-200 rounded-lg" /></label></div></section><section className="bg-white rounded-xl shadow-md p-6"><h2 className="text-xl font-bold text-gray-800 border-b pb-3 mb-5">Información académica y salud</h2><div className="grid md:grid-cols-2 gap-5"><label className="text-sm font-semibold text-gray-700">Grado actual<input value={data.currentGrade} onChange={e => update('currentGrade', e.target.value)} className="mt-1 w-full px-3 py-2 border-2 border-gray-200 rounded-lg" /></label><label className="text-sm font-semibold text-gray-700">Sección<input value={data.section} onChange={e => update('section', e.target.value)} className="mt-1 w-full px-3 py-2 border-2 border-gray-200 rounded-lg" /></label><label className="flex items-center gap-2"><input type="checkbox" checked={data.hasAllergies} onChange={e => setData({ ...data, hasAllergies: e.target.checked })} /> ¿Tiene alergias?</label><label className="flex items-center gap-2"><input type="checkbox" checked={data.hasDiseases} onChange={e => setData({ ...data, hasDiseases: e.target.checked })} /> ¿Tiene enfermedades?</label><textarea placeholder="Descripción de alergias" value={data.allergiesDescription} onChange={e => update('allergiesDescription', e.target.value)} className="border-2 border-gray-200 rounded-lg p-2" /><textarea placeholder="Descripción de enfermedades" value={data.diseasesDescription} onChange={e => update('diseasesDescription', e.target.value)} className="border-2 border-gray-200 rounded-lg p-2" /></div></section><div className="flex justify-center"><button className="px-8 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg shadow">Enviar solicitud de cupo</button></div></form>;
}
