import { useEffect, useState } from 'react';
import { getAccountInfo, requestPasswordCode, resetPassword } from '../../apis/account';
import { toast } from 'react-toastify';
import { FaUserCircle, FaEnvelope, FaIdCard, FaChild, FaKey } from 'react-icons/fa';

export default function InfoAccount() {
  const [account, setAccount] = useState<any>(null);
  const [codeSent, setCodeSent] = useState(false);
  const [form, setForm] = useState({ code: '', newPassword: '', confirmPassword: '' });
  useEffect(() => { getAccountInfo().then((res) => res.result ? setAccount(res.content) : toast.error(res.error?.[0])).catch((error) => toast.error(error.response?.data?.error?.[0] || 'No se pudo cargar la información de la cuenta')); }, []);
  const sendCode = async () => { const res = await requestPasswordCode(); if (res.result) { setCodeSent(true); toast.success(res.content.message); } else toast.error(res.error?.[0]); };
  const savePassword = async () => { const res = await resetPassword(form); if (res.result) { toast.success(res.content.message); setForm({ code: '', newPassword: '', confirmPassword: '' }); setCodeSent(false); } else toast.error(res.error?.[0]); };
  return <div className="max-w-4xl mx-auto space-y-6"><div className="bg-gradient-to-r from-slate-800 to-blue-900 rounded-2xl shadow-lg p-7 text-white"><div className="flex items-center gap-4"><FaUserCircle className="text-5xl text-blue-200" /><div><h1 className="text-3xl font-bold">Información de la cuenta</h1><p className="text-blue-100 mt-1">Tus datos y los estudiantes vinculados a tu cuenta.</p></div></div></div>{account && <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6"><h2 className="text-xl font-bold text-gray-800 mb-5">Datos personales</h2><div className="grid sm:grid-cols-2 gap-4"><div className="rounded-xl bg-blue-50 p-4"><p className="text-xs uppercase text-blue-600 font-bold">Representante</p><p className="mt-1 text-gray-800 font-semibold">{account.representative?.fullName || account.username}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs uppercase text-slate-500 font-bold">Usuario</p><p className="mt-1 text-gray-800 font-semibold">{account.userlogin}</p></div><div className="flex items-center gap-3 rounded-xl border p-4"><FaEnvelope className="text-blue-600" /><div><p className="text-xs text-gray-500">Correo</p><p className="font-medium text-gray-800 break-all">{account.usermail}</p></div></div><div className="flex items-center gap-3 rounded-xl border p-4"><FaIdCard className="text-blue-600" /><div><p className="text-xs text-gray-500">Cédula</p><p className="font-medium text-gray-800">{account.representative?.identityCard || account.identityCard || 'No registrada'}</p></div></div></div></div>}
    <div className="bg-white rounded-2xl shadow-sm border border-gray-200 p-6"><div className="flex items-center gap-3 mb-5"><FaChild className="text-2xl text-blue-600" /><div><h2 className="text-xl font-bold text-gray-800">Alumnos asociados</h2><p className="text-sm text-gray-500">Estudiantes vinculados a esta cuenta.</p></div></div>{account?.representative?.students?.length ? <div className="grid md:grid-cols-2 gap-4">{account.representative.students.map((student: any) => <div key={student.id} className="rounded-xl border border-blue-100 bg-gradient-to-br from-blue-50 to-white p-4"><p className="font-bold text-gray-800">{student.fullName}</p><div className="grid grid-cols-2 gap-2 mt-3 text-sm"><p><span className="text-gray-500">Cédula:</span><br /><b>{student.identityCard || '—'}</b></p><p><span className="text-gray-500">Año:</span><br /><b>{student.currentGrade || student.initialSchoolYear || '—'}</b></p><p><span className="text-gray-500">Sección:</span><br /><b>{student.section || '—'}</b></p><p><span className="text-gray-500">Estado:</span><br /><b className="capitalize">{student.status || '—'}</b></p></div></div>)}</div> : <p className="rounded-xl bg-gray-50 p-4 text-gray-500">No hay alumnos asociados.</p>}</div>
    <div className="bg-gradient-to-br from-blue-50 to-indigo-50 border border-blue-200 rounded-2xl shadow-sm p-6"><div className="flex items-center gap-3"><FaKey className="text-2xl text-blue-700" /><div><h2 className="text-xl font-bold text-blue-950">Seguridad de la cuenta</h2><p className="text-blue-800 text-sm mt-1">Cambia tu contraseña de forma segura usando un código enviado a tu correo.</p></div></div><button onClick={sendCode} className="mt-5 bg-blue-600 hover:bg-blue-700 text-white font-semibold px-5 py-3 rounded-lg shadow-sm">Enviar código para cambiar contraseña</button>
    {codeSent && <div className="space-y-3 border-t border-blue-200 mt-5 pt-5"><input placeholder="Código recibido" value={form.code} onChange={e => setForm({ ...form, code: e.target.value })} className="w-full border p-2 rounded" /><input type="password" placeholder="Nueva contraseña" value={form.newPassword} onChange={e => setForm({ ...form, newPassword: e.target.value })} className="w-full border p-2 rounded" /><input type="password" placeholder="Confirmar contraseña" value={form.confirmPassword} onChange={e => setForm({ ...form, confirmPassword: e.target.value })} className="w-full border p-2 rounded" /><button onClick={savePassword} className="bg-green-600 text-white px-4 py-2 rounded">Confirmar cambio de contraseña</button></div>}</div>
  </div>;
}
