import { useEffect, useState } from 'react';
import { getAccountInfo, requestPasswordCode, resetPassword } from '../../apis/account';
import { toast } from 'react-toastify';

export default function InfoAccount() {
  const [account, setAccount] = useState<any>(null);
  const [codeSent, setCodeSent] = useState(false);
  const [form, setForm] = useState({ code: '', newPassword: '', confirmPassword: '' });
  useEffect(() => { getAccountInfo().then((res) => res.result ? setAccount(res.content) : toast.error(res.error?.[0])).catch((error) => toast.error(error.response?.data?.error?.[0] || 'No se pudo cargar la información de la cuenta')); }, []);
  const sendCode = async () => { const res = await requestPasswordCode(); if (res.result) { setCodeSent(true); toast.success(res.content.message); } else toast.error(res.error?.[0]); };
  const savePassword = async () => { const res = await resetPassword(form); if (res.result) { toast.success(res.content.message); setForm({ code: '', newPassword: '', confirmPassword: '' }); setCodeSent(false); } else toast.error(res.error?.[0]); };
  return <div className="max-w-3xl mx-auto space-y-6"><div className="bg-white rounded-2xl shadow p-6"><h1 className="text-2xl font-bold text-gray-800">Información de la cuenta</h1>{account && <div className="grid md:grid-cols-2 gap-3 mt-5 text-gray-700"><p><b>Nombre:</b> {account.representative?.fullName || account.username}</p><p><b>Usuario:</b> {account.userlogin}</p><p><b>Correo:</b> {account.usermail}</p><p><b>Teléfono:</b> {account.representative?.phone || account.phone || 'No registrado'}</p><p><b>Cédula:</b> {account.representative?.identityCard || account.identityCard || 'No registrada'}</p></div>}</div>
    <div className="bg-white rounded-2xl shadow p-6"><h2 className="text-xl font-bold text-gray-800 mb-4">Alumnos asociados</h2>{account?.representative?.students?.length ? <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="text-left border-b"><th className="p-2">Nombre</th><th className="p-2">Cédula</th><th className="p-2">Año</th><th className="p-2">Sección</th></tr></thead><tbody>{account.representative.students.map((student: any) => <tr key={student.id} className="border-b"><td className="p-2">{student.fullName}</td><td className="p-2">{student.identityCard || '—'}</td><td className="p-2">{student.currentGrade || student.initialSchoolYear || '—'}</td><td className="p-2">{student.section || '—'}</td></tr>)}</tbody></table></div> : <p className="text-gray-500">No hay alumnos asociados.</p>}</div>
    <div className="bg-blue-50 border border-blue-200 rounded-2xl shadow p-6"><h2 className="text-xl font-bold text-blue-900">Cambiar contraseña</h2><p className="text-blue-800 mt-1">Solicita un código de seguridad al correo registrado para actualizar la clave de esta cuenta.</p><button onClick={sendCode} className="mt-4 bg-blue-600 hover:bg-blue-700 text-white font-semibold px-5 py-3 rounded-lg">Enviar código para cambiar contraseña</button>
    {codeSent && <div className="space-y-3 border-t border-blue-200 mt-5 pt-5"><input placeholder="Código recibido" value={form.code} onChange={e => setForm({ ...form, code: e.target.value })} className="w-full border p-2 rounded" /><input type="password" placeholder="Nueva contraseña" value={form.newPassword} onChange={e => setForm({ ...form, newPassword: e.target.value })} className="w-full border p-2 rounded" /><input type="password" placeholder="Confirmar contraseña" value={form.confirmPassword} onChange={e => setForm({ ...form, confirmPassword: e.target.value })} className="w-full border p-2 rounded" /><button onClick={savePassword} className="bg-green-600 text-white px-4 py-2 rounded">Confirmar cambio de contraseña</button></div>}</div>
  </div>;
}
